# Generated by Django 2.0.6 on 2018-11-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PR', 'PR'), ('SR', 'SR')], max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_variation', models.BooleanField(default=False)),
                ('brand_id', models.IntegerField()),
                ('code', models.IntegerField()),
                ('family', models.IntegerField()),
                ('is_complement', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visibility', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('price_offer', models.FloatField(blank=True, null=True)),
                ('offer_day_from', models.DateTimeField(auto_now_add=True, null=True)),
                ('offer_day_to', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField()),
                ('sku', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='product.Product')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'verbose_name_plural': 'Product Details',
                'ordering': ('created',),
            },
        ),
    ]
